spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fixitnow
    username: fixituser
    password: fixit123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



jwt:
  secret: ThisIsASuperSecureSecretKeyForJwtThatShouldBeAtLeast32CharactersLong123
  access-token-expiration: 3900000
  refresh-token-expiration: 604800000
